apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ug-arc-runners
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: util-gitops
    util-gitops.io/category: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: ug-infra
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: "0.14.2"
      helm:
        releaseName: default-runner
        valueFiles:
          - $values/platform/cicd/arc-runners/values.yaml
    - repoURL: https://gitea.util.lcl/AduraX/util-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
