apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ug-cnpg-clusters
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: util-gitops
    util-gitops.io/category: storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: ug-infra
  source:
    repoURL: https://gitea.util.lcl/admin/util-gitops.git
    targetRevision: main
    path: platform/storage/cnpg/clusters
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
