apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ug-routes
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: util-gitops
    util-gitops.io/category: infra
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: ug-infra
  source:
    repoURL: http://gitea-http.devtools.svc.cluster.local:3000/admin/util-gitops.git
    targetRevision: main
    path: gateway-api/routes
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.rules[]?.backendRefs[]?.weight
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
