# HashiCorp Vault CE Helm values (BSL license)
# Chart: hashicorp/vault

server:
  ha:
    enabled: false
  dataStorage:
    enabled: true
    size: 1Gi
  ui:
    enabled: true
    serviceType: ClusterIP
