apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ug-cnpg
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: util-gitops
    util-gitops.io/category: storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: ug-infra
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: "*"
      helm:
        releaseName: cnpg
        valueFiles:
          - $values/platform/storage/cnpg/values.yaml
    - repoURL: https://gitea.util.lcl/AduraX/util-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
