apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ug-kgateway
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: util-gitops
    util-gitops.io/category: infra
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: ug-infra
  sources:
    - repoURL: cr.kgateway.dev/kgateway-dev/charts
      chart: kgateway
      targetRevision: "v2.4.3"
      helm:
        releaseName: kgateway
        valueFiles:
          - $values/infra/base/kgateway/values.yaml
    - repoURL: https://gitea.util.lcl/admin/util-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kgateway-system
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.rules[]?.backendRefs[]?.weight
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
