apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ug-open-webui
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: util-gitops
    util-gitops.io/category: ai
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: ug-infra
  sources:
    - repoURL: https://helm.openwebui.com/
      chart: open-webui
      targetRevision: "*"
      helm:
        releaseName: open-webui
        valueFiles:
          - $values/platform/ai/open-webui/values.yaml
    - repoURL: http://gitea-http.devtools.svc.cluster.local:3000/admin/util-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
