apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ug-traefik
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: util-gitops
    util-gitops.io/category: infra
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: ug-infra
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: "37.2.0"
      helm:
        releaseName: traefik
        valueFiles:
          - $values/infra/base/traefik/values.yaml
    - repoURL: http://gitea-http.devtools.svc.cluster.local:3000/admin/util-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.rules[]?.backendRefs[]?.weight
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
